"""add cid to video_card

Revision ID: 6f8a29b8a86c
Revises: d6e8878321ad
Create Date: 2026-08-31 11:29:22.866442
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f8a29b8a86c'
down_revision: Union[str, None] = 'd6e8878321ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_card', sa.Column('cid', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_card', 'cid')
    # ### end Alembic commands ###
