"""initial

Revision ID: d6e8878321ad
Revises: 
Create Date: 2026-08-31 10:22:46.601815
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6e8878321ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_openid'), 'user', ['openid'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)
    op.create_table('video_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bvid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=False),
    sa.Column('up_name', sa.String(length=128), nullable=False),
    sa.Column('partition', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('pubdate', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bvid', name='uq_video_card_user_bvid')
    )
    op.create_index(op.f('ix_video_card_bvid'), 'video_card', ['bvid'], unique=False)
    op.create_index(op.f('ix_video_card_month'), 'video_card', ['month'], unique=False)
    op.create_index(op.f('ix_video_card_user_id'), 'video_card', ['user_id'], unique=False)
    op.create_table('card_tag',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['video_card.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_tag')
    op.drop_index(op.f('ix_video_card_user_id'), table_name='video_card')
    op.drop_index(op.f('ix_video_card_month'), table_name='video_card')
    op.drop_index(op.f('ix_video_card_bvid'), table_name='video_card')
    op.drop_table('video_card')
    op.drop_index(op.f('ix_tag_user_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_user_openid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###

